# Usa a imagem oficial do MySQL
FROM mysql:latest

# Define variáveis de ambiente para o MySQL (mudar para seus valores)
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
ENV MYSQL_ROOT_PASSWORD=rootpassword

# Expondo a porta padrão do MySQL
EXPOSE 3306
