name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'mysql/**'
      - 'nginx/**'  # Mantém o caminho para a pasta nginx
      - 'docker-compose-backend.yml'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      mysql: ${{ steps.filter.outputs.mysql }}
      nginx: ${{ steps.filter.outputs.nginx }}  # Mudado para nginx
      docker_compose_backend: ${{ steps.filter.outputs.docker_compose_backend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            mysql:
              - 'mysql/**'
            nginx:              # Usando nginx corretamente
              - 'nginx/**'
            docker_compose_backend:
              - 'docker-compose-backend.yml'

  build-and-push:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.mysql == 'true' || needs.changes.outputs.nginx == 'true' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        if: ${{ needs.changes.outputs.backend == 'true' || needs.changes.outputs.mysql == 'true' || needs.changes.outputs.nginx == 'true' }}
        uses: docker/setup-buildx-action@v2

      # Build e Push Backend
      - name: Build and push backend image
        if: needs.changes.outputs.backend == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: joaoluisbeato/backend:latest

      # Build e Push MySQL
      - name: Build and push mysql image
        if: needs.changes.outputs.mysql == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./mysql
          push: true
          tags: joaoluisbeato/mysql:latest

      # Build e Push Frontend (nginx)
      - name: Build and push frontend image
        if: needs.changes.outputs.nginx == 'true'  # Verifica se houve alteração na pasta nginx
        uses: docker/build-push-action@v2
        with:
          context: ./nginx
          push: true
          tags: joaoluisbeato/frontend:latest  # Nome da imagem no Docker Hub
